// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'bronson', 'apps/lib/instagram/views/carouselView', 'apps/lib/instagram/collection/imagesCollection'], function($, _, Backbone, Bronson, CarouselView, ImagesCollection) {
    var InstagramModule;
    return InstagramModule = (function(_super) {

      __extends(InstagramModule, _super);

      InstagramModule.name = 'InstagramModule';

      function InstagramModule(parameters) {
        if (parameters == null) {
          parameters = {};
        }
        this.el = parameters.el;
        InstagramModule.__super__.constructor.apply(this, arguments);
      }

      InstagramModule.prototype.initialize = function() {
        var _this = this;
        this.imagesCollection = new ImagesCollection();
        this.carouselView = new CarouselView({
          collection: this.imagesCollection
        });
        this.imagesCollection.fetch({
          data: {
            client_id: "b3481714257943a4974e4e7ba99eb357",
            lat: "48.858844",
            lng: "2.294351"
          },
          silent: true,
          success: function() {
            return $(_this.el).append(_this.carouselView.render().el);
          }
        });
        Bronson.Core.subscribe('InstagramModule', 'geoUpdate', function(data) {
          return _this.imagesCollection.fetch({
            data: {
              client_id: "b3481714257943a4974e4e7ba99eb357",
              lat: data.latitude,
              lng: data.longitude
            },
            silent: false
          });
        });
        return Bronson.Core.subscribe('InstagramModule', 'dispose', function() {});
      };

      InstagramModule.prototype.dispose = function() {
        return InstagramModule.__super__.dispose.apply(this, arguments);
      };

      return InstagramModule;

    })(Bronson.Module);
  });

}).call(this);
