// Generated by CoffeeScript 1.3.1
(function() {

  require(['underscore', 'backbone', 'bronson'], function(_, Backbone, Bronson) {
    var instagram;
    instagram = false;
    $('#btnAddInstagram').click(function() {
      return Bronson.Core.createModule('apps/lib/instagram/instagramModule', {
        el: '#modules'
      }, function() {
        return instagram = true;
      });
    });
    $('#btnAddTwitter').click(function() {
      return Bronson.Core.createModule('apps/lib/twitter/twitterModule', {
        el: '#modules'
      }, function() {});
    });
    $('#btnAddWeather').click(function() {
      return Bronson.Core.createModule('apps/lib/weather/weatherModule', {
        el: '#modules'
      }, function() {});
    });
    $('#btnAddMaps').click(function() {
      return Bronson.Core.createModule('apps/lib/maps/mapsModule', {
        el: '#modules'
      }, function() {});
    });
    $('#btnAddFourSquare').click(function() {
      return Bronson.Core.createModule('apps/lib/foursquare/foursquareModule', {
        el: '#modules'
      }, function() {});
    });
    return $('#btnGetCurrentPosition').click(function() {
      if (navigator && navigator.geolocation) {
        return navigator.geolocation.getCurrentPosition(function(geo) {
          return Bronson.Core.publish('geoUpdate', geo.coords);
        }, function(error) {
          return console.log('failure');
        });
      } else {
        return console.log('geolocation not supported');
      }
    });
  });

}).call(this);
