// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'bronson', 'text!apps/src/weather/templates/weatherTemplate.html'], function($, _, Backbone, Bronson, WeatherTemplate) {
    var WeatherModule;
    return WeatherModule = (function(_super) {

      __extends(WeatherModule, _super);

      WeatherModule.name = 'WeatherModule';

      function WeatherModule(parameters) {
        if (parameters == null) {
          parameters = {};
        }
        this.el = parameters.el;
        WeatherModule.__super__.constructor.apply(this, arguments);
      }

      WeatherModule.prototype.initialize = function() {
        var _this = this;
        return $.ajax({
          url: "http://api.wunderground.com/api/2d04094a0883bebf/geolookup/conditions/q/IA/Cedar_Rapids.json",
          dataType: "jsonp",
          success: function(parsed_json) {
            var location, temp_f;
            location = parsed_json["location"]["city"];
            temp_f = parsed_json["current_observation"]["temp_f"];
            return $(_this.el).append(_.template(WeatherTemplate, parsed_json));
          }
        });
      };

      WeatherModule.prototype.dispose = function() {};

      return WeatherModule;

    })(Bronson.Module);
  });

}).call(this);
